name: check
run-name: ${{ github.event.pull_request.title || github.event.head_commit.message || format('check {0}', github.ref_name) }}

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop --command bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check source
        run: pnpm run check
